# 使用带有必要工具的基础镜像
FROM alpine:3.13 as nginx-builder

# 安装编译依赖
RUN apk add --no-cache \
    gcc \
    libc-dev \
    make \
    openssl-dev \
    pcre-dev \
    zlib-dev \
    linux-headers \
    libxslt-dev \
    gd-dev \
    geoip-dev \
    perl-dev \
    libedit-dev \
    bash \
    alpine-sdk \
    findutils

# 设置工作目录
WORKDIR /usr/src

# 下载 Nginx 和 ngx_http_echo_module 源代码
ENV NGINX_VERSION 1.21.6
ENV ECHO_MODULE_VERSION 0.62
RUN wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz \
    && tar -zxf nginx-${NGINX_VERSION}.tar.gz \
    && wget https://github.com/openresty/echo-nginx-module/archive/v${ECHO_MODULE_VERSION}.tar.gz \
    && tar -zxf v${ECHO_MODULE_VERSION}.tar.gz

# 编译 Nginx 与 ngx_http_echo_module
RUN cd nginx-${NGINX_VERSION} \
    && ./configure --with-compat --add-dynamic-module=../echo-nginx-module-${ECHO_MODULE_VERSION} \
    && make \
    && make install

# 构建最终镜像
FROM nginx

# 从构建器中复制编译好的 Nginx 和模块
COPY --from=nginx-builder /usr/local/nginx/sbin/nginx /usr/sbin/nginx
COPY --from=nginx-builder /usr/local/nginx/modules/ngx_http_echo_module.so /usr/local/nginx/modules/ngx_http_echo_module.so

# 添加 Nginx 配置文件
COPY nginx.conf /etc/nginx/nginx.conf

# 将构建的前端应用复制到 Nginx
COPY --from=builder /opt/cosd/backend_game/dist /usr/share/nginx/html/

WORKDIR /usr/share/nginx/html
RUN chmod -R a+rx *

# 暴露端口和启动 Nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
