version: '2'

services:
  cosd-web:
    container_name: cosd-web
    image: cosd/cosd-web:1.0
    restart: always
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 8080:8080
    environment:
      - RUNNING_IN_DOCKER=true
